### ISSUE TITLE
line in ggvis 

### ISSUE THREAD

**Issue by wisky90** [wch/movies#2]
Hi! I'm new of Shiny and i ask you: is it possible to add single lines (that have intercept and slope) to ggvis plot? for example with ggplot2 using geom_abline... 
@wch can you help me? ;)

**Comment by wisky90** [comment]
Maybe I didn't explain well: i want to add a line OVER an existent ggvis plot like this of Movie Explorer.
I should add some code here:
movies %>%
      ggvis(x = xvar, y = yvar) %>%
      layer_points(size := 50, size.hover := 200,
        fillOpacity := 0.2, fillOpacity.hover := 0.5,
        stroke = ~has_oscar, key := ~ID) %>%
      add_tooltip(movie_tooltip, "hover") %>%
      add_axis("x", title = xvar_name) %>%
      add_axis("y", title = yvar_name) %>%
      add_legend("stroke", title = "Won Oscar", values = c("Yes", "No")) %>%
      scale_nominal("stroke", domain = c("Yes", "No"), range = c("orange", "#aaa")) %>%
      set_options(width = 500, height = 500)
})
Please @wch can you help me?!

**Comment by wch** [comment]
For right now, you would have to create a data frame and use that as the data for a `mark_path`.

Also, you're more likely to get an answer if you ask on the ggvis mailing list, because there are multiple people who can answer your question there: https://groups.google.com/forum/#!forum/ggvis

**Comment by wisky90** [comment]
Ok, thanks!
